name: Publish and commit bottles
on:
  workflow_dispatch:
    inputs:
      pull_request:
        description: Pull request number
        required: true
      large_runner:
        description: "Run the upload job on a large runner? (default: false)"
        type: boolean
        required: false
        default: false
      autosquash:
        description: "Squash pull request commits according to Homebrew style? (default: false)"
        type: boolean
        required: false
        default: false
      warn_on_upload_failure:
        description: "Pass `--warn-on-upload-failure` to `brew pr-pull`? (default: false)"
        type: boolean
        required: false
        default: false
      message:
        description: "Message to include when autosquashing revision bumps, deletions, and rebuilds (requires autosquash)"
        required: false
permissions:
  actions: write
  contents: write
  packages: write
  pull-requests: write
env:
  PR: ${{inputs.pull_request}}
  HOMEBREW_DEVELOPER: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_FROM_API: 1
  GH_REPO: ${{github.repository}}
  GH_DEBUG: 1
  GH_NO_UPDATE_NOTIFIER: 1
  GH_PROMPT_DISABLED: 1
jobs:
  upload:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/brew:main
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          cask: false

      - name: Configure Git user
        id: git-user-config
        uses: Homebrew/actions/git-user-config@main
        with:
          username: BrewTestBot

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HOMEBREW_GITHUB_PACKAGES_USER: ${{ github.repository_owner }}
          HOMEBREW_GITHUB_PACKAGES_TOKEN: ${{secrets.GITHUB_TOKEN}}
          AUTOSQUASH: ${{inputs.autosquash}}
          WARN_ON_UPLOAD_FAILURE_FLAG: ${{inputs.warn_on_upload_failure && '--warn-on-upload-failure' || ''}}
          MESSAGE: ${{inputs.message}}
        run: |
          sudo sed -i 's/Closes ##{pr}/[skip ci]/g' "$(brew --repository)"/Library/Homebrew/dev-cmd/pr-pull.rb
          args=(
            --debug
            --workflows=build.yml
            "--tap=${GITHUB_REPOSITORY_OWNER}/php"
            "--root-url=https://ghcr.io/v2/${GITHUB_REPOSITORY_OWNER}/php"
          )
          if [[ "${AUTOSQUASH}" == "true" ]]; then
            args+=(--autosquash)
          else
            args+=(--clean)
          fi
          if [[ -n "${WARN_ON_UPLOAD_FAILURE_FLAG}" ]]; then
            args+=("${WARN_ON_UPLOAD_FAILURE_FLAG}")
          fi
          if [[ -n "${MESSAGE}" ]]; then
            args+=("--message=${MESSAGE}")
          fi
          args+=("${PR}")
          brew pr-pull "${args[@]}"

      - name: Merge PR branch
        working-directory: ${{steps.set-up-homebrew.outputs.repository-path}}
        run: bash .github/scripts/retry.sh 10 10 gh pr merge "$PR" --auto --delete-branch --rebase
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Push commits
        uses: Homebrew/actions/git-try-push@main
        with:
          directory: ${{steps.set-up-homebrew.outputs.repository-path}}
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Sync branches
        run: gh workflow run sync-default-branches.yml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
